### ISSUE TITLE
Erratic Zoom on macOS

### ISSUE THREAD

**Issue by ma7moudat** [nextapps-de/spotlight#1]
Hi!

Looks really elegant, nicely done!

Just had in issue on macOS Mojave using Chrome v74. When I open one the galleries and happen to scroll horizontally using the Magic Mouse or the trackpad, the image would suddenly either
a) get extremely zoomed in until only a couple pixels are visible, or..
b) disappear from the viewport entirely

Seems like when zooming with scroll, the CSS transform would reach some extreme values like `scale(2.22699e+12);` so a limit should be set!

**Comment by ts-thomas** [comment]
Late answer, the zoom was limited in the meanwhile.
