### ISSUE TITLE
Custom options do not work

### ISSUE THREAD

**Issue by Mexikaner9** [nextapps-de/spotlight#11]
First of all thank you very much for this great lightbox!
	
Unfortunately my custom options are ignored.
I think I made a fundamental mistake or forgot something fundamental, but I don't know what.
Can someone please help me?
I am using this code:

`
window.showGallery = function(index){
Spotlight.show(gallery, {
 animation: "flip",
 theme: "white",
 autohide: false,
 control: ["autofit", "zoom", "player", "page"]
});
};

`

Here is my example:
http://nirvana.bplaced.net/spotlight/

Thanks in advance

**Comment by ts-thomas** [comment]
Thanks for the nice words. It is a bug, the code example looks good. The 0.7.0 is coming soon, which has including a fix for it. In the meanwhile try to assign the options to the DOM elements via data-attributes (e.g. to the "spotlight-group" element). That should work.

**Comment by Mexikaner9** [comment]
Thank you very much for your answer and your help!

**Comment by Mexikaner9** [comment]
Ich finde diese Lightbox richtig klasse! Viele Optionen und trotzdem ein Leichtgewicht und benötigt auch kein jquery. Recht herzlichen Dank dafür!

**Comment by darksnake747** [comment]
The interesting thing is that it works on the demo site in 0.6.5. That demo uses the API and it works fine with no errors and custom options. It uses the bundle.js not the dist/min.js; but I can't seem to see why it works and my (nearly) exact copy of the example in my application does not work.

**Comment by Wahrheit26** [comment]
I have the same problem as Mexikaner9
I would be happy if the bug is fixed

**Comment by ts-thomas** [comment]
The API usage was slightly broken, the focus was probably too much on the markup paradigm. This is now fixed in version >= 0.7.0

Thanks for your patience.
