### ISSUE TITLE
New button / function

### ISSUE THREAD

**Issue by mac2001** [nextapps-de/spotlight#13]
Hi, 
great library! Very useful and very well-looking.

My question is if there is a possibility to add own buttons in an easy way - for instance to manipulate the image (change colors) or download the file?
It would be great if I can define just an image for new function and implement this functionality as JS function.
Maciej

**Comment by ts-thomas** [comment]
Custom buttons are now supported by the version >= 0.7.0, the full documentation is on the road. An example of a custom button in the toolbar is on the demo page last example, the like icon with its logic when clicked is fully added by the new method "addControl".

**Comment by adaniello** [comment]
@ts-thomas Thanks for updates but i think that this request concern an easy way to add a new button in toolbar and not in footer.
Thanks
