### ISSUE TITLE
Dynamic load of prev/next images

### ISSUE THREAD

**Issue by mac2001** [nextapps-de/spotlight#14]
Hi,
another question. I'd like to open just one image, but have arrow buttons (left/right) triggering loading another image with JS function (e.g. with AJAX). So, at the moment of showing spotlight I know only one image, but when clicking right arrow, another image should be loaded. Is it possible with the bundle version or I should modify original code?

**Comment by mac2001** [comment]
I experimented a bit and I have a workaround, but perhaps there is more flexible solution. Anyway, to make arrows always visible, this works:

`.arrow { visibility: visible !important; }`

Then I am able to use events for these left and right DIV elements (sorry, for testing - just with jquery):

`$('.arrow-left').click(function() { $('#spotlight div.pane img').attr("src", "gallery/1.jpg"); });`
`$('.arrow-right').click(function() { $('#spotlight div.pane img').attr("src", "gallery/2.jpg"); });`

Should I do something more in order to avoid some problems with the library later?

**Comment by ts-thomas** [comment]
What I can see so far from your code, that this is will inject the image when clicking on the arrow buttons. But that is the default behavior of the arrow images, or isn't?

**Comment by ts-thomas** [comment]
Ok I realize the problem. The next version will provide custom events for prev and next in addition to the already existing onchange event. Your current workaround will be compatible.

**Comment by mac2001** [comment]
Thank you, Thomas. In general, I think, that the more customization possible, the better. I cross my fingers for your development, the library is really useful and has very nice look-and-feel.

**Comment by johnkendall** [comment]
Just to add support to this. I have thousands of images and want to be able to load using ajax. Looking forward to it in 0.7. Good work :)

**Comment by ts-thomas** [comment]
Preloading the next image in line is already supported and enabled by default. Preloading the previous image is actually not supported. I already thought about Left-To-Right support which can cover this also. You need just pass all images to the spotlight gallery and it is preloading them for your automatically. Also you could use the callback "onchange" to bypass custom code when sliding. Combined with the new feature "custom node fragments" you could make your own "image object" and bypass the internal image handler completely. The full documentation about node fragments as a slide will follow and is actually on the demo page.
