### ISSUE TITLE
Only errors ...

### ISSUE THREAD

**Issue by stelasido** [nextapps-de/spotlight#18]
Sorry, but your library is full of bugs ..... I see for the first time so  many bugs in one library.
1. You CAN'T use Spotlight with only one param or you will get an error
2.  You need always to use title for images array or you guess it ...
`client.js?ver=1577689873:117245 Uncaught TypeError: (t || document).getElementsByTagName is not a function`
3. If you are using Spotlight .close(), then open the gallery and try to change the image, yes 👍 
`client.js?ver=1577690024:117241 Uncaught TypeError: Cannot read property 'length' of null`

These all are when I am using JS to set the gallery.

**Comment by stelasido** [comment]
You need to specify and an argument `Spotlight.close(true)`. and bad documentation .

**Comment by ts-thomas** [comment]
The good thing about open source projects is, that anyone can contribute ...
