### ISSUE TITLE
Lots of potential...

### ISSUE THREAD

**Issue by David-Carty** [nextapps-de/spotlight#19]
spotlight.bundle.js:9 Uncaught TypeError: Cannot read property 'length' of undefined
    at l (spotlight.bundle.js:9)
    at La (spotlight.bundle.js:16)
    at spotlight.bundle.js:31

Using on SPA.  Don't have the time to look into the whys at the moment.  But all of my code looks fine and is working well, just seems that this lib is fragile.  Shame really because the small code base makes it full of potential when compared to other lightboxes.  Look forward to the update. D

**Comment by darksnake747** [comment]
https://github.com/nextapps-de/spotlight/issues/21 may help you out. I was having similar issues. Good luck @David-Carty !

**Comment by tsukumijima** [comment]
In my environment, it was improved by modifying it as follows. For your information.
https://github.com/tsukumijima/spotlight/commit/573954f5be168aac8cd76298252420c70ffe87ab

**Comment by ts-thomas** [comment]
Would be nice if you can check this issue on the new version >= 0.7.0, theoretically it shouldn't occur anymore. I can't test it fully because I cannot reproduce this issue.
