### ISSUE TITLE
When version 0.7.0

### ISSUE THREAD

**Issue by mac2001** [nextapps-de/spotlight#20]
Dear Thomas,
when can we expect v. 0.7.0? Do you have any time schedule for this next release? 
Best regards,
Maciej

**Comment by adaniello** [comment]
No news about v. 0.7.0?

**Comment by sayontan** [comment]
Any updates on this? The announcement on the landing page says:

> Spotlight 0.7.0 is coming soon during Dezember 2020, packed with fixes of all the github posted issues also a lot of feature requests like video support or embedding a gallery inline.

**Comment by adaniello** [comment]
Hi, it there any updates about 0.7.0? Any feedback is appreciated.

Thanks

**Comment by ts-thomas** [comment]
it has arrived finally :)
