### ISSUE TITLE
Calling Spotlight.show() with option {theme: "white"} toggles between dark and white themes

### ISSUE THREAD

**Issue by RemusVasii** [nextapps-de/spotlight#23]
The issue can be tested on the demo page by changing the line:

https://github.com/nextapps-de/spotlight/blob/40c8e47d08993c9b41ed65182f90086c34460649/demo/index.html#L82

to

theme: "white"

When using the SHOW buttons (opening and closing the gallery several times), the theme will toggle between white and dark.

Currently, the white theme can be set only by using the following trick:

theme: document.getElementById("spotlight").classList.contains("white") ? "dark" : "white"

**Comment by ts-thomas** [comment]
The theme handler was broken and is now improved on the version >= 0.7.0, please try again.
