### ISSUE TITLE
Request: additional autohide on title

### ISSUE THREAD

**Issue by tefod-zz** [nextapps-de/spotlight#26]
Hi,
in advance - sorry for abusing the issue-tracker for a feature request.

An additional autohide for the footer/title would be really great. 
Sometime there are elements in the picture which are been covered of the footer-bar/title.

Thx :)
Regards.

**Comment by ts-thomas** [comment]
That's a good suggestion. I will add this to the list of feature requests.

**Comment by ts-thomas** [comment]
This is now supported by the new version 0.7.3, just set the option `autohide` to the value "all" instead of true/false. Great suggestion, thanks.
