### ISSUE TITLE
Add a download option / button for the currently displayed image 

### ISSUE THREAD

**Issue by FraaErasmas** [nextapps-de/spotlight#28]
Is it possible to download the picture that is displayed, or at least get its url with right click + copy image address ?

**Comment by vwswebmaster** [comment]
I came here to ask for the same thing. A user asked me how to download an image from the slider and I thought for sure there would be a way, but apparently not! This would be a great way to protect images you didn't want (less savvy) people to be able to download, but an option to allow downloads would be great.

**Comment by bw984** [comment]
I also would find this feature extremely useful in my application utilizing spotlight.  I may attempt a pull request for this feature if that's okay?

**Comment by ts-thomas** [comment]
It is now supported

https://github.com/nextapps-de/spotlight/issues/36
