### ISSUE TITLE
Are PDF image and Tiff image not view?

### ISSUE THREAD

**Issue by Seema-SoftwareDeveloper** [nextapps-de/spotlight#30]

**Comment by ts-thomas** [comment]
Tiff should be loaded if the browser supports it. PDF is not an image at all but you can do this now with the version >= 0.7.0 by adding a iframe as a slide along the url to the pdf.

Create a hidden backstore which includes the node you want to add as a slide:

```html
<div style="display: none">
    <iframe id="pdf-viewer" src="path/to/file.pdf"></iframe>
</div>
```

Assign the iframe (node) as a media for the slide:
```html
<a class="spotlight" data-media="node" data-src="#pdf-viewer">
    Click to open PDF
</a>
```

That should basically work, but probably could be optimized further like assigning the source closely right before the gallery opens. This could be done via callbacks (onshow, onchange, onclose).
