### ISSUE TITLE
Close gallery on click

### ISSUE THREAD

**Issue by ccarlosm** [nextapps-de/spotlight#31]
Hi!,

First of all, thanks for developing this amazing package.

I have not found an option to enable closing on mouse click. Does it exist the feature?

Thanks very much!

**Comment by ccarlosm** [comment]
Ok, Easy peasy.

$('#spotlight').on('click', function () {
    Spotlight.close();
})

**Comment by tefod-zz** [comment]
This won't work if the #spotlight element ist not added to the DOM already.
It must be listen/bind to an upper element (document, body etc.). This worked for me:
```
$(document).on('click', '#spotlight', function () {
	Spotlight.close();
});
```

**Comment by MaluNoPeleke** [comment]
How to use this together with markup instead of API? Only clicking on the empty (black) parts should close the spotlight view.
This doesn't get active:
```
[].forEach.call(document.querySelectorAll('#spotlight'), function(el) {
    el.addEventListener('click', function() { 
      Spotlight.close();
    })
  })
```
