### ISSUE TITLE
AMP Support

### ISSUE THREAD

**Issue by AidanHak** [nextapps-de/spotlight#34]
I'm using [AMP](https://amp.dev) for my website. Is there any way Spotlight can work with the `amp-img` and `amp-carousel` components? Since at the moment Spotlight requires wrapping each image in an anchor element, but `amp-carousel` does not behave properly with anchor elements wrapped around each image (`amp-img`).

Perhaps a way of doing this by adding the class to the image itself rather than to a wrapped anchor element?

**Comment by ts-thomas** [comment]
You do not need to apply the "spotlight" class to an anchor element only, you can add this class to any element.

https://github.com/nextapps-de/spotlight#non-anchor-elements

```html
<div class="spotlight" data-src="img1.jpg">
    <img src="thumb1.jpg">
</a>
```
