### ISSUE TITLE
Could we have a download feature when I show a image?

### ISSUE THREAD

**Issue by theodore74** [nextapps-de/spotlight#36]
Could we have a download feature when showing an image?
If I put thumbnail in the img src, I don't wanna download thumbnail. But I could not download when I click and show an image (save as will save to a html .

**Comment by ts-thomas** [comment]
It is now supported by default in version >= 0.7.0, I will add some documentation to this feature, but long story short just add a control flag "download", e.g.:

```html
<a class="spotlight" href="cat1.jpg" data-control="download,zoom,autofit,close">
    <img src="cat1-thumb.jpg">
</a>
```

**Comment by bw984** [comment]
Awesome!  Thank you so much!
