### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by ArminMueller** [nextapps-de/spotlight#4]
I have the following error message when using Chrome browser
Unable to preventDefault inside passive event listener invocation

**Comment by ts-thomas** [comment]
Is this an error message (red color) or an info message (yellow color)?

**Comment by ts-thomas** [comment]
Sounds like you use an older version (current is 0.6.3). I checked the code, there a just 2 listener which are passive, and both skips the call of `event.preventDefault()`.

**Comment by ArminMueller** [comment]
The problem is gone with 0.6.3

**Comment by ArminMueller** [comment]
i must correct promlem still exists. the problem occures on mobile when using swipe

**Comment by ts-thomas** [comment]
This problem is finally solved in https://github.com/nextapps-de/spotlight/tree/0.6.5
