### ISSUE TITLE
iOS safari seems not able to view picture with v0.7. Please help to confirm the issue.

### ISSUE THREAD

**Issue by theodore74** [nextapps-de/spotlight#40]
I just tested 0.7. It is great in windows and android.
but iOS9 Safari seems had problem to view picture.

I also tested the https://nextapps-de.github.io/spotlight/ with iOS9, There are only first row images ("Anchors & Images") able to be opened, the rest images just don't open.

ps: I don't have latest iOS device right now, maybe someone could tested and report?

**Comment by ts-thomas** [comment]
Thanks for the report. I will made some test on iOS9 and come back soon with a result.

**Comment by theodore74** [comment]
The issue was fixed in v.074.
Thank you for the great work.

**Comment by ts-thomas** [comment]
Great. I've tested it also now and can confirm it works fine. Thanks for the report.
