### ISSUE TITLE
It seems losing cookie/session while viewing an image under iOS safari. 

### ISSUE THREAD

**Issue by theodore74** [nextapps-de/spotlight#41]
It seems losing cookie/session while viewing an image under iOS safari. 
(It works fine under windows and android. )

I just got a Mac 10.14 to test.
when I use iOS safari 13, it hang up while viewing an image, the loading loop will never end.
It seems cookie/session is missing therefore the loading is corruptted, BUT I click "download", the image will be downloaded successfully with successful authentication.

Maybe the viewing entity and download entity are different ?

please advice.

**Comment by ts-thomas** [comment]
Could you send me a screenshot please which shows the issue? An issue with cookie/session sounds strange, probably that issue is not produced by Spotlight. Can you remove the lib temporary and proof if the cookie issue still exist? Thanks in advance.

**Comment by theodore74** [comment]
Hi.
Thanks for quick reply.

Because the debug is at server side, I could not reproduce the same environment for you.

I have a test method for your reference.


In your demo download (spotlight-master)
In Custom element section, find an image data-src , just replace it to 
https://mrmad.com.tw/wp-content/uploads/2020/04/windows-vmware-player-macos-10-15-catalina-31.jpg
or
https://nextapps.de/img/logo-nextapps.svg

and add “data-control=”download, close” 


Then  browse the local demo , ex:  http://127.0.0.1/spotlight-master/index.html
click the custom element “modified” image to confirm the issue.


--
Best Regards,
Team John Long Software Co. Ltd.
Arnor 
Email: ***@***.***
TEL: +886-2-29573457

**Comment by ts-thomas** [comment]
Thanks for the example. I've found the issue. It was a CORS issue when loading crossOrigin images. I removed the crossOrigin flag from the image, it should fix it. Probably when downloading an image which is stored on a different domain you have to explicitly enable CORS on the server on which the images are served.

**Comment by ts-thomas** [comment]
the fix is included in 0.7.4

**Comment by theodore74** [comment]
Hi,
I did several tests, it should be OK.
Thank you for the great work!

For now, I think the only issue I got here is while viewing pictures on safari/edge/opera, 
the image (jpg) orientation didn’t work well as chrome and firefox.

--
Best Regards,
Team John Long Software Co. Ltd.
Arnor 
Email: ***@***.***
TEL: +886-2-29573457
