### ISSUE TITLE
The full screen icon is sometimes missing in demo

### ISSUE THREAD

**Issue by ajax333221** [nextapps-de/spotlight#42]
It disappears and/or re-appears randomly and sometimes it's missing from start, examples:
- If I enter to 2/3 the icon is missing and going to 3/3 and then back to 2/3 makes it appear again.
- If I click on the 3/3 image on demo, and navigate to 2/3 it reappears, but then in 1/3 it goes missing again.

Is the demo like this for all of you or I'm having some cache issues?

**Comment by ajax333221** [comment]
pretty weird, also the second row shows the same snow house but upon clicking I get the waterfall, I'm starting to think this is cache related but this even happens on incognito and after I try to hard-refresh (but I think my laptop doesn't hard-refresh just with ctrl+f5 so idk).

**Comment by ajax333221** [comment]
I really tried on incognito and to hard-refresh the browser, but I'm getting the same thing.

Also the first pic on the second row (the snowy house) leads to waterfall, I would normally open another ticket for this but I'm starting to thing it's a cache thing on my end so I will save myself some embarrassment and wait a little bit to see what's going on here.

**Comment by ts-thomas** [comment]
You are right. That is not a bug, the first image has the option `data-fullscreen="false"` so that is the desired behavior. I've added this just for testing purposes and forgot to remove it. Will be removed in next commit. Thanks for the report.
