### ISSUE TITLE
New button in toolbar

### ISSUE THREAD

**Issue by adaniello** [nextapps-de/spotlight#43]
@ts-thomas Thanks for updates but i think that this request concern an easy way to add a new button in toolbar and not in footer.
Thanks

_Originally posted by @adaniello in https://github.com/nextapps-de/spotlight/issues/13#issuecomment-832448732_

**Comment by ts-thomas** [comment]
https://github.com/nextapps-de/spotlight#custom-controls

;)

**Comment by adaniello** [comment]
Ops! Thanks
