### ISSUE TITLE
Are you planning to add close the image via swipe down?

### ISSUE THREAD

**Issue by nickicool** [nextapps-de/spotlight#44]
Hi! I really like spotlight, but lack the ability to close an open image via a swipe gesture (for example, swipe down, as in popular apps). Are you planning to add this in future releases?

**Comment by ts-thomas** [comment]
https://github.com/nextapps-de/spotlight#pending-feature-suggestions

Yes it is on my list. The problem of that swipe-down-to-close feature is the concurrency between both axis when sliding. It will introduce a lot of side-effects ... the majority of interactions is the sliding to left or right, that should not be interrupted by the possibility to slide down. Also the new version support embedding of fragments which can have its own vertical scrollbar theoretically, that will collide also. I did not say it will never come, of course it is still on the list, but that isn't something which could just implemented, the big challenge is to find a smart workaround (e.g. through an axis threshold) which does not interrupt the natural feel of horizontal sliding which is 1000% more important than sliding down.
