### ISSUE TITLE
Firefox scrollbar bugs

### ISSUE THREAD

**Issue by TravisCardwell** [nextapps-de/spotlight#46]
I ran across scrollbar bugs on Firefox.  I see them on Firefox 88.0 (64-bit on Arch Linux).  Here are the steps to reproduce the bugs:

1. Navigate to the [demo](https://nextapps-de.github.io/spotlight/)
2. Click one of the images in the top row
    * The spotlight UI is shown in the whole document area.
    * BUG: The browser shows a scrollbar.  Expected behavior: there should be no scrollbar (confirmed in Google Chrome).
3. Click the full screen icon at the top right (second icon from the right)
    * The spotlight UI is displayed full screen.
    * The scrollbar is no longer displayed.
4. Press escape to exit full screen.
    * The spotlight UI is shown in the whole document area.
    * The scrollbar is still not displayed.
5. Click the close icon at the top right (right-most icon)
    * The spotlight UI is closed, returning to the demo page.
    * BUG: The demo page no longer has a scrollbar and cannot be scrolled.  The page needs to be reloaded to bring the scrollbar back.  Expected behavior: there should be a scrollbar and the page should be scrollable.

**Comment by ts-thomas** [comment]
Thanks a lot, that was a perfect bug report. I didn't notice this strange issue with Firefox. It should be fixed now in v0.7.62. When exit Fullscreen the fullscreen icon disappears, I will fix that also, but that's not as critical as this issue you've posted.
Thanks a lot!
