### ISSUE TITLE
Disable zoomIn/zoomOut on scroll

### ISSUE THREAD

**Issue by ontomas** [nextapps-de/spotlight#47]
I've disabled the zoomIn and zoomOut buttons via the API, but there seems to be no way of disabling zooming on scroll as some default js kicks in. Any way to work around this? I'm trying to add a `overflow-y: scroll` with cover class to enable scrolling of long images.

**Comment by ts-thomas** [comment]
I will extend the flag `data-zoom="false"` to disable zooming also via keyboard control and mousewheel. I also will remove `zoom-in` and `zoom-out` to be separated and replace this with this just `zoom` for both directions.

**Comment by ts-thomas** [comment]
The last update v0.7.72 disables zoom also for mousewheel and keyboard when controls/buttons are disabled.
