### ISSUE TITLE
Using video sources with the api

### ISSUE THREAD

**Issue by ddrury** [nextapps-de/spotlight#52]
Using the option src-{format} generates an error
```
{
   src-mp4: mymovie.mp4,
  poster: ...
  etc.
} 
```
generates a console error

> Cannot play media. No decoders for requested formats: video/-mp4

ie it looks like the hyphen between src and mp4 is not being removed

**Comment by ts-thomas** [comment]
This is now fixed in the latest version. Thanks a lot for the report.
