### ISSUE TITLE
CSS suggestion

### ISSUE THREAD

**Issue by ddrury** [nextapps-de/spotlight#55]
In my site (which I didn't write) the global css file has the following
```
.wt-global {
    overflow-y: scroll;
    overflow-x: hidden;
}
```
which is applied to the body, this over-rides spotlight's class hide-scrollbars css. Can I suggest you add `!important` to the overflow: hidden line. After all very little (none?) of the theme css is applicable when spotlight is active.

**Comment by ts-thomas** [comment]
This is now included on the latest version. Thanks a lot for the report.
