### ISSUE TITLE
Button that opens Spotlight

### ISSUE THREAD

**Issue by bshinholser** [nextapps-de/spotlight#56]
Thanks so much for your effort on this plugin. It's super quick and solves my problem nicely!

Currently I'm implementing Spotlight using the bundle. 

**What's working:** I have the `.spotlight-group` class on the main container and then applying the `.spotlight` class directly to the image containers so if a user clicks on an image in the carousel, it'll launch the Spotlight modal. This works seamlessly.

**What's not working:** I have a button on the UI so the user can click to open the modal and zoom/pan the images. I haven't had any success at getting the Spotlight modal to open the gallery normally when clicking the button.

To clarify, I need the UI element to open the existing spotlight gallery when clicked, just like clicking "Show" on the demo to launch a gallery instance. Is there an existing method or example to make this happen? If not, it would be a useful feature.

**Comment by ts-thomas** [comment]
Thank you very much. Did you tried something like this:

```html
<button class="spotlight" data-src="img/picture.jpg">Click Me</button>
```

You can add this to every element.

**Comment by bshinholser** [comment]
@ts-thomas I have tried using the class on the button. The issue with that -- if I have 4 images in the carousel within `.spotlight-group` and I have the `<button class="spotlight" data-src=""></button>`, the button becomes an extra slide instead of just being a trigger. In the attached screenshot, you'll see the icon in the bottom-right -- that's the expand button. All the images in the carousel have the spotlight class, so if you click the image it launches Spotlight. That is working great, I just cannot figure out how to get the button to work with this case.

![Screen Shot 2021-06-21 at 11 32 56 AM](https://user-images.githubusercontent.com/4692127/122788679-927b4400-d284-11eb-8d31-a5071b3aae6b.png)
