### ISSUE TITLE
Cannot use the package with Package Manager (NPM)

### ISSUE THREAD

**Issue by kfirba** [nextapps-de/spotlight#6]
Hey.

It seems to be impossible to use the package with a package manager. When I install the package, I can't just import it and use it:

```js
import Spotlight from 'spotlight.js'; // This gives an empty object {}
```

You seem to miss the `main` entry in your `package.json` file. Also, your module does not declare any export definition. The only way to use your package is to manually download it or via CDN. Is that intentional or is it something you can fix?

Thanks

**Comment by ts-thomas** [comment]
The Spotlight image gallery is a browser-based tool. Therefore this library runs only in a Browser. The node package is just for using with a build system (webpack, etc.). 

Actually the ES6-module-loader from Node.js v12 requires the experimental flag `--experimental-modules` and also did not work properly for some reason. I would like to wait until this feature is officially released. Maybe someone can provide a workaround which works also for Node.js and Browser.

**Comment by kfirba** [comment]
@ts-thomas I'm not sure I fully understand. I do get it that this is a browser-based tool, however, it does not mean it cannot be built and served for the web using a package manager. Usually what you do in these cases is that you write your code in ES6 and use some kind of tool to compile your code to javascript that every browser understands. All you need is a `prepublish` hook that simply compiles your code to ES5 and you're good to go.

I thought about maybe having my build process copy the files from the `node_modules` but the `spotlight.js` file contains some references to files that do not exist:

```js
import stylesheet from "../../tmp/style.js";
import template from "../../tmp/template.js";
```

Is there anything I can do to help you?

**Comment by ts-thomas** [comment]
To make temporary files available, please run `npm run build`. Before you can also configure some flags in the "src/js/config.js" file. The build process also compiles ES6 to ES5. The final build is located in the "dist" folder.

**Comment by kfirba** [comment]
@ts-thomas Why does this package needs a build step? The optimal use would be to simply import the CSS and JS into my file and then invoke the script:

```js
import 'spotlight.js/dist/spotlight.css';
import Spotlight from 'spotlight.js';

// Code to invoke Spotlight here
```

Wouldn't that be preferable? I'm trying to think if I can somehow "automate" the build process with webpack. How would you do this?

**Comment by ts-thomas** [comment]
The build takes your custom settings into account. The final *.css file is dependent on the settings you use (e.g. inline base64 encoded images, external image files, cdn images). Also the css is combinable with the js file (bundled version) or could be loaded as separated. Thats why there exist temporary files (pre-built). I am also not really happy with this workaround, however I have not found a better way yet.

I could add a pre-built hook to the package.json, would that help you?

**Comment by kfirba** [comment]
@ts-thomas Let's try to break it down.

What you want to be able to do is to let people choose which features of the package they want, right?
I think that in order to do allow for it while also being compatible with a package manager, you can take the approach of "plugins".

What I would do is create multiple "plugin" files in my src directory and if a user wants to use them, he will import that file and "use" it, similar to `Vue.js` and its ecosystem:

```
import Vue from 'vue'; // The core library
import VueRouter from 'vue-router'; // A router plugin

Vue.use(VueRouter);

// In your case:
import Spotlight from 'spotlight.js'
import PluginA from 'spotlight.js/plugins/PluginA';

Spotlight.use(PluginA);
// or
new Spotlight({
  plugins: [PluginA],
});
```

This way you allow people to require just the plugins/functionality they want.

About the CSS, you should ship with some default implementation (maybe inline base 64 encoded images - as many packages do) but expose some way for the user to specify that he wants to use image files (during run-time, not build time) and maybe even specify his own image.

Ship the package with some sensible defaults and set up some ways for the user to override certain parts of it easily. The images issue is easily solvable by shipping the package with a default but let people specify their own image path as an option. This way, CDN users will just get the defaults and use it that way (also allowing them to override the images if they wish for it) and package manager users can further optimize their build.

What do you think?

**Comment by kfirba** [comment]
@ts-thomas I would love to assist with changing the library architecture if we decide what we want it to look like. Let me know.

**Comment by rockneverdies55** [comment]
First make it easily usable please... This process should be as simple (or standard) as...   
`npm install spotlight.js --save`
`import Spotlight from 'spotlight.js'`
  
Then improve it by making some things optional if you really want to.

**Comment by ts-thomas** [comment]
The latest update may fix your issues. Please try again.

**Comment by ts-thomas** [comment]
The upcoming version (0.7.0) will provide production ready ES6 modules and solves the problem with build flags.

**Comment by TheNemus** [comment]
Any news about 0.7.0?

**Comment by ts-thomas** [comment]
Please test again the usage as a npm package. I also made some improvements of the build system. It should work flawless by now.

**Comment by damirbogd** [comment]
@ts-thomas 

still happening for me in spotlight.js@0.7.7
`import Spotlight from 'spotlight.js'; // This gives an empty object {}`

**Comment by damirbogd** [comment]
@ts-thomas 
reproducible example in Vue on [Codesanbox](https://codesandbox.io/s/eloquent-keldysh-x9v13?file=/src/App.vue)

**Comment by dantio** [comment]
This issue is still open.
We need a commonJs build since es6 is not always compatible and bundlers won't bundle it out of the box.

1. "main" in package.json should point to a commonJS build (for backward compatibility)
2. "module" in package.json that point to "src/js/spotlight.js"
