### ISSUE TITLE
Loading the library after DOMContentLoaded event

### ISSUE THREAD

**Issue by kfirba** [nextapps-de/spotlight#7]
Hey @ts-thomas.

There is an issue that when I attempt to load the library after the DOMContentLoaded event had already been fired, the gallery does not work.

My scenario is relatively simple. I don't want the user to download the library on the initial page rendering, thus I use dynamic import to download the library after the user can see some content (since the gallery is not the main feature of the page). By doing so, it seems like the library is not registering itself properly due to it expecting to respond to the `DOMContentLoaded` event.

The easiest fix I can think of is to export the logic of the `DOMContentLoaded` into a function which you also bind to the `Spotlight` object:

```js
// Turn this:
addListener(document, "DOMContentLoaded", function() {...}, {once: true});

// To this:
function init() {
  // code...
}

addListener(document, "DOMContentLoaded", init, {once: true});

// ...

/* Export API */

window["Spotlight"] = {

    "init": init, // <-- The addition
    "theme": theme,
    "fullscreen": fullscreen,
    "autofit": autofit,
    "next": next,
    "prev": prev,
    "goto": goto,
    "close": close,
    "zoom": zoom,
    "menu": menu,
    "show": show,
    "play": play
};
```
Now in my script I could just call `Spotlight.init()`.

What do you think?

**Comment by kfirba** [comment]
@ts-thomas Any news about this?

**Comment by ts-thomas** [comment]
Thanks for the fix, this workaround is pretty nice 👍

**Comment by ts-thomas** [comment]
Merged in https://github.com/nextapps-de/spotlight/commit/31f2ff6e252035009d528747afa30881211276be
